### ISSUE TITLE
About occlusion mask

### ISSUE THREAD

**Issue by HuTaoMylove** [idiap/GeoNeRF#10]
thank you for your work!
I do not understand why you mask the point which d upper than D, Volume rendering could deal with this kind of points.could you give me some suggestion?tks!

**Comment by MohammadJohari** [comment]
Hello,

The occlusion masks are taken into account before the volume rendering when we aggregate the information from all source images in a self-attention architecture. Occluded images will inject noisy information into the attention architecture and it helps to exclude them explicitly.

I hope this helps.
