### ISSUE TITLE
Table 1: Comparisons with the SOTA

### ISSUE THREAD

**Issue by basit-7** [idiap/GeoNeRF#13]
You mentioned in the paper that, "The evaluations of the baselines on the DTU MVS dataset [23] are borrowed from the paper MVSNeRF [6]". Is this the case for LLFF and NeRF synthetic as well? I have not been able to reproduce results mentioned in MVSNeRF paper, wanted to confirm if that was the case for you as well.

**Comment by MohammadJohari** [comment]
Yes, that is correct. We were not able to reproduce the results from MVSNeRF. Therefore, I reported the numbers from their paper. For IBRNet, however, I reported the numbers from the original paper as the numbers in MVSNeRF were not fair to them.
