### ISSUE TITLE
GPU Memory needed for evaluation

### ISSUE THREAD

**Issue by zsh2000** [idiap/GeoNeRF#5]
Hi, thanks for publishing your code for the excellent work!

When I was using the code to evaluate the model, I found myself come across "CUDA out of memory" even though I have cut the "chunk " in configuration to a very small number (64). I'm using 4 GeForce RTX 2080 GPUs, and I want to know how much GPU memory is needed for model evaluation.

By the way, I found that maybe it is only able to use one GPU, since no matter how many GPUs I assign in the CUDA_VISIBLE_DEVICES, memory from only one GPU is taken up, then the process is killed.

Best regards,
Shuhong

**Comment by code-EEEE** [comment]
@zsh2000 Hi, there is something wrong with my env, it will be helpful if you show me your conda list.

**Comment by MohammadJohari** [comment]
@zsh2000

Hello,

RTX 2080 unfortunately cannot run our inference code with default parameters. You can however reduce nb_views = 9 parameter in the config files to reduce memory usage. That will result in lower quality rendering though.

I suspect the memory limit in your case is due to our geometry reasoner backbone, and it does not support multi-GPU inference sadly.

Best,

**Comment by zsh2000** [comment]
@MohammadJohari 

Thank you for your reply! By the way does the model support multi-GPU in the training time?

**Comment by zsh2000** [comment]
Hi @code-EEEE 

This is my conda list:

_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_kmp_llvm
absl-py=1.2.0=pypi_0
aiohttp=3.8.1=pypi_0
aiosignal=1.2.0=pypi_0
async-timeout=4.0.2=pypi_0
attrs=22.1.0=pypi_0
blas=2.116=mkl
blas-devel=3.9.0=16_linux64_mkl
bzip2=1.0.8=h7f98852_4
ca-certificates=2022.6.15.2=ha878542_0
cachetools=5.2.0=pypi_0
certifi=2022.6.15.2=pypi_0
charset-normalizer=2.1.1=pypi_0
configargparse=1.5.3=pypi_0
cudatoolkit=10.2.89=h713d32c_10
decorator=5.1.1=pypi_0
frozenlist=1.3.1=pypi_0
fsspec=2022.8.2=pypi_0
future=0.18.2=pypi_0
google-auth=2.11.0=pypi_0
google-auth-oauthlib=0.4.6=pypi_0
grpcio=1.48.1=pypi_0
idna=3.4=pypi_0
imageio=2.21.3=pypi_0
importlib-metadata=4.12.0=pypi_0
inplace-abn=1.1.1.dev6+gd2728c8=pypi_0
ipdb=0.13.9=pypi_0
kornia=0.6.7=pypi_0
ld_impl_linux-64=2.36.1=hea4e1c9_2
libblas=3.9.0=16_linux64_mkl
libcblas=3.9.0=16_linux64_mkl
libffi=3.4.2=h7f98852_5
libgcc-ng=12.1.0=h8d9b700_16
libgfortran-ng=12.1.0=h69a702a_16
libgfortran5=12.1.0=hdcd56e2_16
libgomp=12.1.0=h8d9b700_16
liblapack=3.9.0=16_linux64_mkl
liblapacke=3.9.0=16_linux64_mkl
libnsl=2.0.0=h7f98852_0
libsqlite=3.39.3=h753d276_0
libstdcxx-ng=12.1.0=ha89aaad_16
libuuid=2.32.1=h7f98852_1000
libzlib=1.2.12=h166bdaf_3
llvm-openmp=14.0.4=he0ac6c6_0
lpips=0.1.4=pypi_0
markdown=3.4.1=pypi_0
markupsafe=2.1.1=pypi_0
mkl=2022.1.0=h84fe81f_915
mkl-devel=2022.1.0=ha770c72_916
mkl-include=2022.1.0=h84fe81f_915
multidict=6.0.2=pypi_0
ncurses=6.3=h27087fc_1
networkx=2.8.6=pypi_0
numpy=1.23.3=pypi_0
oauthlib=3.2.1=pypi_0
opencv-python=4.6.0.66=pypi_0
openssl=3.0.5=h166bdaf_2
pandas=1.4.4=pypi_0
pillow=9.2.0=pypi_0
pip=22.2.2=pyhd8ed1ab_0
protobuf=3.19.5=pypi_0
pyasn1=0.4.8=pypi_0
pyasn1-modules=0.2.8=pypi_0
pydeprecate=0.3.0=pypi_0
pyparsing=3.0.9=pypi_0
python=3.8.13=ha86cf86_0_cpython
python-dateutil=2.8.2=pypi_0
pytorch=1.12.1=py3.8_cuda10.2_cudnn7.6.5_0
pytorch-lightning=1.3.7=pypi_0
pytorch-mutex=1.0=cuda
pytz=2022.2.1=pypi_0
pywavelets=1.3.0=pypi_0
pyyaml=5.4.1=pypi_0
readline=8.1.2=h0f457ee_0
requests=2.28.1=pypi_0
requests-oauthlib=1.3.1=pypi_0
rsa=4.9=pypi_0
scikit-image=0.19.3=pypi_0
scipy=1.9.1=pypi_0
setuptools=65.3.0=pyhd8ed1ab_1
six=1.16.0=pypi_0
sqlite=3.39.3=h4ff8645_0
tbb=2021.5.0=h924138e_2
tensorboard=2.10.0=pypi_0
tensorboard-data-server=0.6.1=pypi_0
tensorboard-plugin-wit=1.8.1=pypi_0
test-tube=0.7.5=pypi_0
tifffile=2022.8.12=pypi_0
tk=8.6.12=h27826a3_0
toml=0.10.2=pypi_0
torchmetrics=0.6.0=pypi_0
torchvision=0.13.1=pypi_0
tqdm=4.64.1=pypi_0
typing_extensions=4.3.0=pyha770c72_0
urllib3=1.26.12=pypi_0
werkzeug=2.2.2=pypi_0
wheel=0.37.1=pyhd8ed1ab_0
xz=5.2.6=h166bdaf_0
yarl=1.8.1=pypi_0
zipp=3.8.1=pypi_0

I find pytorch 1.9 may have some issues, so I choose to pytorch 1.12 instead.

**Comment by MohammadJohari** [comment]
@zsh2000 
No, our implementation only supports single GPU training.
