### ISSUE TITLE
DTU dataset

### ISSUE THREAD

**Issue by caiyongqi** [idiap/GeoNeRF#6]
Loading dtu datasets seems to be a little different from MVSNeRF, why is that?
https://github.com/idiap/GeoNeRF/blob/e6249fdae5672853c6bbbd4ba380c4c166d02c95/data/dtu.py#L161
` self.interval_scale = 1.06`

**Comment by caiyongqi** [comment]
Anybody？

**Comment by MohammadJohari** [comment]
This is because MVSNeRF uses preprocessed images for the dtu dataset, while we load images from the original dataset (https://roboimagedata.compute.dtu.dk/?page_id=36). The images in preprocessed are cropped, so we need to modify the camera parameters to match the original dataset.

**Comment by TimChou-ntu** [comment]
Hi, I'm doing generalized neural radiance field lately. I wonder why you don't just use preprocessed images as MVSNeRF did. 
Is there any reason?

Thanks in advance.

**Comment by MohammadJohari** [comment]
The preprocessed dtu images are cropped, and consequently, some parts of the objects are missing in some of the cropped images. This has no benefit and only disrupts our pre-training phase as the network has no access to ground truth inputs in some training batches. We found no reason not to use the original images of the dtu dataset.
