### ISSUE TITLE
Why use the training mode when testing

### ISSUE THREAD

**Issue by caiyongqi** [idiap/GeoNeRF#7]
https://github.com/idiap/GeoNeRF/blob/e6249fdae5672853c6bbbd4ba380c4c166d02c95/run_geo_nerf.py#L318
This seems to imply that BN will store the distribution (mean and variance) of the test data.

**Comment by MohammadJohari** [comment]
This is also done in MVSNeRF, and we found it useful. It does not store the distribution of test data. It calculates the distribution of the test data instantly and normalizes the input itself. Similarly to InstanceNorm.
